version: '3'
services:
  frontend:
    build: ./example-frontend
    expose:
      - 5000
    container_name: fr-app
  backend:
    build: ./example-backend
    expose:
      - 8080
    environment:
      - REDIS_HOST=db
      - POSTGRES_HOST=pg
    container_name: b-app
  db:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  pg:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432
  proxy:
    image: nginx
    volumes:
      - /home/snehil/Desktop/learning/docker/ex1-11/material-applications/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
