version: '3'
services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=db
  db:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
