version: '3'
services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=db
      - POSTGRES_HOST=pg
  db:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  pg:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432
